import break1 from "../images/break1.jpg";
import break2 from "../images/break2.jpg";
import break3 from "../images/break3.jpg";
import lunch1 from "../images/lunch1.webp";
import lunch2 from "../images/lunch2.webp";
import lunch3 from "../images/lunch3.jpg";
import dinner1 from "../images/dinner1.webp"
import dinner2 from "../images/dinner2.webp"
import dinner3 from "../images/dinner3.webp"



const initState={
    recipes: [
        {namefr:"Oeufs brouillés au gruyère, bacon et épinards ",ingredientsfr:"8 gros œufs, 1 c. Moutarde de Dijon, sel et poivre casher, 1 c. huile d'olive ou beurre non salé,2 tranches de bacon épaisses cuites et coupées en morceaux,2 c. épinards déchirés, 2 oz. Fromage Gruyère, râpést",stepsfr:"1-Dans un grand bol, fouetter ensemble les œufs Moutarde de Dijon 1 cuillère à soupe d'eau et 1/2 cuillère à café de sel et de poivre.,2-Chauffer l'huile ou le beurre dans une poêle antiadhésive de 10 pouces à feu moyen. Ajouter les œufs et cuire en remuant avec une spatule en caoutchouc toutes les quelques secondes, jusqu'à la cuisson désirée 2 à 3 minutes pour des œufs mi-mous. Incorporer les épinards au bacon et le gruyère.",name:"Gruyère, Bacon, and Spinach Scrambled Eggs", car_category:"breakfast", ingredients:"8 large eggs,1 tsp. Dijon mustard,Kosher salt and pepper,1 tbsp. olive oil or unsalted butter,2 slices thick-cut bacon cooked and broken into pieces,2 c. spinach torn,2 oz. Gruyère cheese, shredded",steps:"1-In a large bowl whisk together eggs Dijon mustard 1 tablespoon water and 1/2 teaspoon each salt and pepper.,2-Heat oil or butter in 10-inch nonstick skillet on medium. Add eggs and cook stirring with rubber spatula every few seconds, to desired doneness 2 to 3 minutes for medium-soft eggs. Fold in bacon spinach and Gruyère cheese.", image:break1},
        {namefr:"Muffins Quinoa Aux Très Baies",ingredientsfr:"3/4 c. farine tout usage,1 c. farine d'amande, 1/4 c. quinoa blanc (cru), 1 c. levure chimique, 1 c. cannelle moulue, 1/2 c. gingembre moulu, 1/2 c. bicarbonate de soude, 1/2 c. sel casher, 2 gros œufs battus, 1 c. yogourt nature entier, 1/4 c. lait entier, 1/3 c. miel, 2 contenants de 6 oz petites framboises",stepsfr:"1. Chauffer le four à 325 °F. Enduire légèrement un moule à 12 muffins d'un enduit à cuisson et saupoudrer de farine. ,2. Dans un grand bol; mélanger les farines; le quinoa; la poudre à pâte; la cannelle; le gingembre; et le bicarbonate de soude et le sel. ,3. Dans un bol moyen; fouetter ensemble les œufs; le yogourt; le lait et le miel. Incorporer le mélange d'œufs au mélange de farine jusqu'à ce qu'il soit juste combiné puis incorporer les framboises.,4. Répartir la pâte dans les moules à muffins et cuire jusqu'à ce qu'un cure-dent inséré au centre des muffins en ressorte propre 15 à 20 minutes. Laisser refroidir dans le moule 5 minutes puis transférer sur une grille pour refroidir complètement.",name:"Very Berry Quinoa Muffins", car_category:"breakfast", ingredients:"3/4 c. all-purpose flour,1 c. almond flour,1/4 c. white quinoa (raw),1 tsp. baking powder,1 tsp. ground cinnamon,1/2 tsp. ground ginger,1/2 tsp. baking soda,1/2 tsp. kosher salt,2 large eggs beaten,1 c. plain full-fat yogurt,1/4 c. whole milk,1/3 c. honey ,2 6-oz containers small raspberries",steps:"1. Heat oven to 325°F. Lightly coat 12-cup muffin pan with cooking spray and dust with flour. ,2. In large bowl whisk together flours quinoa baking powder cinnamon ginger baking soda and salt. ,3. In medium bowl whisk together eggs yogurt milk and honey. Fold egg mixture into flour mixture until just combined, then stir in raspberries.,4. Divide batter among muffin-pan cups and bake until toothpick inserted into centers of muffins comes out clean 15 to 20 minutes. Cool in pan 5 minutes then transfer to a wire rack to cool completely." , image:break2 },
        {namefr:"Beignets à la cannelle",ingredientsfr:"Spray de cuisson avec de la farine, 2 tasses de farine tout usage, 1 1/2 tasse de sucre, 2 cuillères à café de levure chimique, 1 cuillère à café de cannelle moulue, 1/2 cuillère à café de muscade moulue, 1/2 cuillère à café de sel casher, 1 œuf extra-large, légèrement battu, 1 1/4 tasse de lait entier, 2 cuillères à soupe de beurre non salé fondu, 2 cuillères à café d'extrait de vanille pur",stepsfr:"1- Préchauffer le four à 350 degrés. Vaporisez bien 2 moules à beignets., 2-Dans un grand bol, tamisez ensemble la farine le sucre la levure chimique la cannelle la muscade et le sel. Dans un petit bol, fouetter ensemble le lait d'œuf, le beurre fondu et la vanille. Incorporer le mélange humide aux ingrédients secs jusqu'à ce qu'ils soient tout juste combinés. Enfournez 17 minutes, jusqu'à ce qu'un cure-dent en ressorte propre. Laissez refroidir 5 minutes, puis tapotez les beignets sur une plaque à pâtisserie., 4-Pour la garniture, faites fondre les 8 cuillères à soupe de beurre dans une sauteuse de 8 pouces. Mélanger le sucre et la cannelle dans un petit bol. Tremper chaque beignet d'abord dans le beurre puis dans le sucre à la cannelle, d'un côté ou des deux côtés.",name:"Cinnamon Baked Doughnuts", car_category:"breakfast", ingredients:"Baking spray with flour,2 cups all-purpose flour ,1 1/2 cups sugar ,2 teaspoons baking powder ,1 teaspoon ground cinnamon ,1/2 teaspoon ground nutmeg ,1/2 teaspoon kosher salt ,1 extra-large egg, lightly beaten ,1 1/4 cups whole milk ,2 tablespoons unsalted butter melted ,2 teaspoons pure vanilla extract ",steps:"1- Preheat the oven to 350 degrees. Spray 2 doughnut pans well., 2-Into a large bowl sift together the flour sugar baking powder cinnamon nutmeg and salt. In a small bowl whisk together the egg milk melted butter and vanilla. Stir the wet mixture into the dry ingredients until just combined., 3-Spoon the batter into the baking pans, filling each one a little more than three-quarters full. Bake for 17 minutes, until a toothpick comes out clean. Allow to cool for 5 minutes, then tap the doughnuts out onto a sheet pan., 4-For the topping, melt the 8 tablespoons of butter in an 8-inch saute pan. Combine the sugar and cinnamon in a small bowl. Dip each doughnut first in the butter and then in the cinnamon sugar, either on one side or both sides." , image:break3 },
        {namefr:"Sandwich au fromage grillé épicé",ingredientsfr:"2 cuillères à soupe de beurre ou de margarine, 4 tranches de pain blanc, 2 tranches de fromage américain, 1 tomate roma (prune), tranchée finement, ¼ petit oignon haché, 1 piment jalapeno, haché",stepsfr:"Chauffer une grande poêle à feu doux. Étaler du beurre ou de la margarine sur un côté de deux tranches de pain. Placer les deux morceaux côté beurré vers le bas dans la poêle. Déposez une tranche de fromage sur chacun et garnissez de tranches de tomate, d'oignon et de jalapeño. Beurrer un côté des tranches de pain restantes et placer dessus, côté beurré vers le haut. Lorsque le fond des sandwichs est grillé, retournez-le et faites-le frire jusqu'à ce qu'il soit doré de l'autre côté.",name:"Spicy Grilled Cheese Sandwich", car_category:"lunch", ingredients:"2 tablespoons butter or margarine,4 slices white bread,2 slices American cheese,1 roma (plum) tomato, thinly sliced,¼ small onion chopped,1 jalapeno pepper, chopped",steps:"Heat a large skillet over low heat. Spread butter or margarine onto one side of two slices of bread. Place both pieces buttered side down in the skillet. Lay a slice of cheese on each one, and top with slices of tomato, onion and jalapeno. Butter one side of the remaining slices of bread, and place on top buttered side up. When the bottom of the sandwiches are toasted, flip and fry until brown on the other side." , image:lunch1 },
        {namefr:"Banh Mi",ingredientsfr:"½ tasse de vinaigre de riz, ¼ tasse d'eau, ¼ tasse de sucre blanc, tasse de carottes, coupées en allumettes de 1/16 po d'épaisseur, ¼ tasse de radis blanc (daikon), coupés en allumettes de 1/16 po d'épaisseur, ¼ tasse oignon blanc émincé,1 demi-poitrine de poulet désossée et sans peau,ail sel au goût poivre noir moulu au goût,1 (12 pouces) baguette française,4 cuillères à soupe de mayonnaise,¼ tasse de concombre tranché finement,1 cuillère à soupe de feuilles de coriandre fraîche,1 petit piment jalapeño - épépiné et coupé en allumettes de 1/16 de pouce d'épaisseur, 1 quartier de citron vert",stepsfr:"",name:"Banh Mi",car_category:"lunch", ingredients:"½ cup rice vinegar,¼ cup water,¼ cup white sugar,¼ cup carrot, cut into 1/16-inch-thick matchsticks,¼ cup white (daikon) radish, cut into 1/16-inch-thick matchsticks,¼ cup thinly sliced white onion,1 skinless, boneless chicken breast half,garlic salt to tasteground black pepper to taste,1 (12 inch) French baguette,4 tablespoons mayonnaise,¼ cup thinly sliced cucumber,1 tablespoon fresh cilantro leaves,1 small jalapeno pepper - seeded and cut into 1/16-inch-thick matchsticks,1 wedge lime", steps:"1-Place rice vinegar water and sugar into a saucepan over medium heat bring to a boil and stir until the sugar has dissolved about 1 minute. Allow the mixture to cool.,2-Pour the cooled vinegar mixture over the carrot, radish, and onion in a bowl, and allow to stand for at least 30 minutes. Drain off the excess vinegar mixture after the vegetables have marinated.,3-To assemble the bahn mi sandwich, spread each half of the toasted baguette with mayonnaise, and fill the cavity of the bottom half of the bread with broiled chicken, cucumber slices, pickled carrot, onion, and radish, cilantro leaves, and jalapeno pepper. Squeeze a wedge of lime over the filling, and top with the other half of the baguette." , image: lunch2},
        {namefr:"Pizza",ingredientsfr:"½ tasse de vinaigre de riz, ¼ tasse d'eau, ¼ tasse de sucre blanc, tasse de carottes, coupées en allumettes de 1/16 po d'épaisseur, ¼ tasse de radis blanc (daikon), coupés en allumettes de 1/16 po d'épaisseur, ¼ tasse oignon blanc émincé,1 demi-poitrine de poulet désossée et sans peau,ail sel au goût poivre noir moulu au goût,1 (12 pouces) baguette française,4 cuillères à soupe de mayonnaise,¼ tasse de concombre tranché finement,1 cuillère à soupe de feuilles de coriandre fraîche,1 petit piment jalapeño - épépiné et coupé en allumettes de 1/16 de pouce d'épaisseur, 1 quartier de citron vert",stepsfr:"1-Pour la sauce : combiner tous les ingrédients de la sauce avec 1/2 tasse d'eau dans un bol moyen ; mettre de côté pour que les saveurs se développent tout en faisant la croûte. Congeler le reste de la pâte.,2-Pour les croûtes : mélanger 2 tasses de farine avec la levure sèche, le sucre et le sel. Ajouter l'eau et l'huile et mélanger jusqu'à homogénéité (environ 1 minute). Ajouter graduellement assez de farine restante lentement jusqu'à ce qu'une boule de pâte molle et collante se forme. 3-Diviser la pâte en deux. Tapoter chaque moitié (avec les mains farinées) dans un moule à pizza graissé de 12 pouces OU rouler la pâte pour s'adapter aux moules.,4-Faire cuire au four pendant 18 à 20 minutes jusqu'à ce que les croûtes soient dorées et que le fromage bouillonne. Pour de meilleurs résultats, faites pivoter les plaques à pizza entre les grilles supérieure et inférieure du four à mi-cuisson.",name:"pizza",car_category:"lunch", ingredients:"½ (12 ounce) can CONTADINA® Tomato Paste,1 teaspoon dried oregano, crushed,1 teaspoon dried basil crushed,½ teaspoon garlic powder,½ teaspoon onion powder,½ teaspoon sugar,½ teaspoon salt,¼ teaspoon black pepper",steps:"1-For sauce: Combine all sauce ingredients with 1/2 cup water in a medium bowl; set aside for flavors to develop while making crust. Freeze remaining paste .,2-For crusts: Combine 2 cups of flour with the dry yeast sugar and salt. Add the water and oil and mix until well blended (about 1 minute). Gradually add enough remaining flour slowly until a soft sticky dough ball is formed.3-Divide dough in half. Pat each half (with floured hands) into a 12-inch greased pizza pan OR roll dough to fit pans.,4-Bake for 18 to 20 minutes until crusts are browned and cheese is bubbly. For best results rotate pizza pans between top and bottom oven racks halfway through baking." , image:lunch3 },
        {namefr:"Pâtes au pesto de brocoli",ingredientsfr:"Fleurons de brocoli,Basilic frais,Ail frais,Pignons de pin,Huile d'olive extra vierge,Parmigiano-Reggiano,Et un ingrédient secret : l'eau de cuisson des pâtes réservée",stepsfr:"1-Préparez tous vos ingrédients au pesto de brocoli - rincez les feuilles de basilic, râpez votre parmesan, épluchez votre ail.,2-Portez à ébullition une grande casserole d'eau salée.,3-Faites bouillir le brocoli. Au bout de deux minutes, retirez les fleurons et ajoutez vos pâtes.,4-Pendant la cuisson des pâtes, préparez le pesto ! Mélanger le brocoli, le basilic, l'ail, les pignons, l'huile d'olive extra vierge, le sel et le parmigiano reggiano jusqu'à ce qu'il soit bien lisse.,5-Lorsque les pâtes sont cuites, prélevez une tasse de cet or liquide (alias eau de pâte) et ajoutez lentement au pesto pendant que vous le mélangez un peu plus.6,-Mélanger les pâtes avec le pesto de brocoli et creuser!",name:"Broccoli Pesto Pasta", car_category:"dinner", ingredients:"Broccoli florets,Fresh basil,Fresh garlic,Pine nuts,Extra virgin olive oil,Parmigiano-Reggiano,And one secret ingredient: reserved pasta cooking water", steps:"1-Prep all of your broccoli pesto ingredients—rinse the basil leaves, grate your Parmigiano, peel your garlic.,2-Bring a big pot of salted water to a boil.,3-Boil the broccoli. After two minutes, remove the florets, and add your pasta.,4-While the pasta cooks, make the pesto! Blend the broccoli, basil, garlic, pine nuts, extra virgin olive oil, salt and parmigiano reggiano until it’s nice and smooth.,5-When the pasta is done, scoop out a cup of that liquid gold (aka pasta water) and add it slowly to the pesto as you blend it a bit more.6,-Toss the pasta with the broccoli pesto and dig in!" , image: dinner1},
        {namefr:"Poulet au citron",ingredientsfr:"Poulet, Citron, Ail, Toutes les herbes que vous voulez",stepsfr:"1-Nettoyez le poulet,2-Prenez un bol et mettez le poulet,3-Pressez 2 citrons et ajoutez n'importe quelle herbe que vous aimez,4-Cuisez au four pendant 15 minutes",name:"Lemon Chicken", car_category:"dinner", ingredients:"Chicken, Lemon, Garlic, Any herbs you want", steps:"1-Clean the Chicken,2-Get a bowl and put the chicken,3-Squeeze 2 lemons and add any herb you like,4-Bake for 15 minutes" , image:dinner2 },
        {namefr:"Marinara de poulet en pot instantané avec polenta",ingredientsfr:"Cuisses de poulet, Marinara, Un peu de sel",stepsfr:"1-Déposez les cuisses de poulet salées et la sauce tomate dans votre Instant Pot.,2-Cuisez à puissance élevée pendant 5 minutes.,3-Laissez la pression se relâcher naturellement pendant 10 minutes.4-Râpez les cuisses de poulet dans la sauce et servez !st",name:"Instant Pot Chicken Marinara With Polenta",car_category:"dinner", ingredients:"Chicken thighs, Marinara, A little salt", steps:"1-Dump the salted chicken thighs and tomato sauce into your Instant Pot.,2-Cook on high for 5 minutes.,3-Let the pressure release naturally for 10 minutes.4-Shred the chicken thighs in the sauce, and serve!" , image:dinner3 },
    ]
};

const rootReducer=(state=initState)=> {
    return state;
};

export default rootReducer